services:
  mysql:
    image: mysql:8.0 # versão do MySQL, pode trocar se quiser
    container_name: javafx_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root  # define a senha do usuário root
      MYSQL_DATABASE: agencia_data              # cria um banco de dados automaticamente
    ports:
      - "3309:3306"  # mapeia a porta do container para sua máquina
    volumes:
      - mysql_data:/var/lib/mysql  # volume para persistir os dados

volumes:
  mysql_data:
